// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bizici-refresh/BusinessCurrent.tsx": () => import("../components/mockups/bizici-refresh/BusinessCurrent.tsx"),
  "./components/mockups/bizici-refresh/BusinessShops.tsx": () => import("../components/mockups/bizici-refresh/BusinessShops.tsx"),
  "./components/mockups/bizici-refresh/ConsumerCurrent.tsx": () => import("../components/mockups/bizici-refresh/ConsumerCurrent.tsx"),
  "./components/mockups/bizici-refresh/ConsumerDiscovery.tsx": () => import("../components/mockups/bizici-refresh/ConsumerDiscovery.tsx")
};
